# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FEditor' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FEditor

  pod "WordPress-Aztec-iOS"
  pod "WordPress-Editor-iOS"

end
