# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'chatDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for chatDemo
  
  # 计时器
  pod 'SwiftyTimer'
  
  # 网络图片加载
  pod 'Kingfisher'
  
  # AutoLayout
  pod 'SnapKit'

end
