# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'pictureWindow' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for pictureWindow

  # 图片库
  pod 'Kingfisher'
  
  # 提示窗
  pod 'FTIndicator'

end
